\ProvidesClass{SebastianResume}
\LoadClass[11pt,a4paper,sans]{moderncv}

%% ModernCV themes
\moderncvstyle{casual}
\moderncvcolor{blue}
\renewcommand{\familydefault}{\sfdefault}
\nopagenumbers{}

\usepackage[utf8]{inputenc}
\usepackage[scale=0.75]{geometry}

\firstname{Sebastian}
\familyname{Lenartowicz}
\title{ Problem Solver}
\address{\#1010, 45 Oakmount Road}{Toronto, ON M6P 2M4}
\mobile{(519)~400~8185}
\email{sebastian.lenartowicz.one@gmail.com}
\social[github]{NGTOne}
\quote{What needs doing today?}